### ISSUE TITLE
dataset examples?

### ISSUE THREAD

**Issue by antithing** [jutanke/mv3dpose#3]
Hi, and thank you for making this code available. 

Is there an existing dataset that will work out of the box? 

I have the 'Campus' set, but I don't see the `camera.json` files. Do I need to create these? 

Thanks again!

**Comment by antithing** [comment]
Ah, I have found the preprocessing scripts. thanks!

**Comment by minhhoangbui** [comment]
@antithing Did you succeed to train or use the code?
After investigating the preprocessing code, I still struggle to understand how to make framexxx.json file?
Thank you very much
