### ISSUE TITLE
Using this code online?

### ISSUE THREAD

**Issue by antithing** [jutanke/mv3dpose#4]
Hi, and thank you for making this code available. 

I am looking to adopt it for real time online use. Before I dig too far into it, is this possible with this code?

I plan to:

```
Calibrate N Cameras.
While frames:
    Grab 1 frame from each camera
    Pose detection in each frame.
    Pass single frame keypoints and Calibration data to your code
    Receive 3d poses / points back per frame.
```

Is this likely to work without too much refactoring? 
Thank you!

**Comment by jutanke** [comment]
Hi,
this is tricky using the code "as is", as it currently works in "steps":
* extract 2d poses for all cameras for all frame
* extract 3d poses using the 2d skeletons + camera params for all frames
* Gaussian smooth the 3d poses across time and space

In principle, the algorithm can work online, and the algorithm is actually quite simple [(Please check out the paper)](http://pages.iai.uni-bonn.de/gall_juergen/download/jgall_mvpose_gcpr19.pdf) - so re-implementing it (with the help of this repo) should not be too difficult.

The reason for the "steps" approach was that the original OpenPose code was a bit difficult to make work, so I wrapped it into a docker container. But you can use ANY method that extracts multiple 2d human poses from images, not just OpenPose!

**Comment by antithing** [comment]
Great! thank you. I will attempt it. :)

**Comment by jutanke** [comment]
I would guess this answers the question, I will close the issue. If you have any problems with the paper or with the code, just re-open this issue or create a new one.

Cheers

**Comment by aviralchharia** [comment]
Hey, I was trying to implement the repository for online tracking. Any suggestions on the choice of backbone for 2D Keypoint extraction (apart from OpenPose), whose runtime happens to be independent of the number of persons in the frame?
