### ISSUE TITLE
Docker image pull access denied

### ISSUE THREAD

**Issue by sowd** [jutanke/mv3dpose#5]
Hi, did you close the public docker image? So sad..

> Unable to find image 'jutanke/mv3dpose:latest' locally
> docker: Error response from daemon: pull access denied for jutanke/mv3dpose, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Shigeru

**Comment by jutanke** [comment]
@sowd did you build the image? I think the documentation is a bit lacking in that regard.

```
cd docker && ./build.sh
```

Also, did you add your user to the *docker* group? [(docker post-install)](https://docs.docker.com/engine/install/linux-postinstall/)
