### ISSUE TITLE
Camera config file?

### ISSUE THREAD

**Issue by minhhoangbui** [jutanke/mv3dpose#6]
As I can see, in order to set up fundamental matrix using opencv, we need to have config file in json for each camera. How to get that file? Do we need to get a checkerboard for that?
Thank you very much

**Comment by jutanke** [comment]
@minhhoangbui No checkerboard is required - you just need calibrated cameras. For each camera, you need a json file with the following structure:
```
{
  "P" : [ 3 x 4 ],
  "w" : int(width),
  "h" : int(height)
}
```

OR 

```
{
  "K" : [ 3 x 3 ], /* intrinsic paramters */
  "rvec": [ 1 x 3 ], /* rotation vector */
  "tvec": [ 1 x 3 ], /* translation vector */
  "discCoef": [ 1 x 5 ], /* distortion coefficient */
  "w" : int(width),
  "h" : int(height)
}
```

The cameras in this follow OpenCV standards so if you used OpenCV to calibrate you're good to go

**Comment by edwardnguyen1705** [comment]
@jutanke 
As I understand, K is fixed for each cam after calibration, but extrinsic paremeters  rvec and tvec vary from image to image. Or I misunderstand about rvec and tvec?

**Comment by jutanke** [comment]
@edwardnguyen1705 as long as you have the camera params (`K`, `rvec`, `tvec`) for each time step it does not matter if they change or not. The datasets used for this repo all use fixed cameras throughout the recordings.
