### ISSUE TITLE
`EPFL_Campus` Function in campus.py of Preprocessing Dir

### ISSUE THREAD

**Issue by aviralchharia** [jutanke/mv3dpose#7]
What does EPFL_Campus function represent in `from pak.datasets.EPFL_Campus import EPFL_Campus`? Its in the `campus.py` file of the pre-processing folder.

**Comment by jutanke** [comment]
This comes from this library: https://github.com/jutanke/pak

The library is outdated and un-maintained so use it at your own discretion. It should still load the data.

**Comment by aviralchharia** [comment]
Thanks for sharing!
